<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\GymClassSchedule;
use Carbon\Carbon;

class GymClassScheduleSeeder extends Seeder
{
    public function run(): void
    {
        $schedules = [
            [
                'date' => Carbon::today()->addDays(1),
                'start_time' => '08:00:00',
                'end_time' => '09:00:00',
                'slot' => 15,
                'gym_class_id' => 1,
            ],
            [
                'date' => Carbon::today()->addDays(1),
                'start_time' => '15:00:00',
                'end_time' => '16:00:00',
                'slot' => 15,
                'gym_class_id' => 1,
            ],
            [
                'date' => Carbon::today()->addDays(2),
                'start_time' => '10:00:00',
                'end_time' => '11:00:00',
                'slot' => 15,
                'gym_class_id' => 1,
            ],
            [
                'date' => Carbon::today()->addDays(3),
                'start_time' => '15:00:00',
                'end_time' => '16:00:00',
                'slot' => 15,
                'gym_class_id' => 1,
            ],
            [
                'date' => Carbon::today()->addDays(4),
                'start_time' => '08:00:00',
                'end_time' => '09:00:00',
                'slot' => 15,
                'gym_class_id' => 1,
            ],
            [
                'date' => Carbon::today()->addDays(5),
                'start_time' => '15:00:00',
                'end_time' => '16:00:00',
                'slot' => 15,
                'gym_class_id' => 1,
            ],
            [
                'date' => Carbon::today()->addDays(6),
                'start_time' => '10:00:00',
                'end_time' => '11:00:00',
                'slot' => 15,
                'gym_class_id' => 1,
            ],
            [
                'date' => Carbon::today()->addDays(7),
                'start_time' => '15:00:00',
                'end_time' => '16:00:00',
                'slot' => 15,
                'gym_class_id' => 1,
            ],
            [
                'date' => Carbon::today()->addDays(1),
                'start_time' => '08:00:00',
                'end_time' => '09:00:00',
                'slot' => 20,
                'gym_class_id' => 2,
            ],
            [
                'date' => Carbon::today()->addDays(1),
                'start_time' => '10:30:00',
                'end_time' => '11:30:00',
                'slot' => 20,
                'gym_class_id' => 2,
            ],
            [
                'date' => Carbon::today()->addDays(1),
                'start_time' => '13:00:00',
                'end_time' => '14:15:00',
                'slot' => 20,
                'gym_class_id' => 2,
            ],
            [
                'date' => Carbon::today()->addDays(2),
                'start_time' => '09:00:00',
                'end_time' => '10:00:00',
                'slot' => 20,
                'gym_class_id' => 2,
            ],
            [
                'date' => Carbon::today()->addDays(2),
                'start_time' => '15:00:00',
                'end_time' => '16:00:00',
                'slot' => 20,
                'gym_class_id' => 2,
            ],
            [
                'date' => Carbon::today()->addDays(1),
                'start_time' => '07:00:00',
                'end_time' => '08:00:00',
                'slot' => 10,
                'gym_class_id' => 3,
            ],
            [
                'date' => Carbon::today()->addDays(1),
                'start_time' => '10:00:00',
                'end_time' => '11:00:00',
                'slot' => 10,
                'gym_class_id' => 3,
            ],
            [
                'date' => Carbon::today()->addDays(2),
                'start_time' => '13:00:00',
                'end_time' => '14:30:00',
                'slot' => 10,
                'gym_class_id' => 3,
            ],
            [
                'date' => Carbon::today()->addDays(2),
                'start_time' => '15:30:00',
                'end_time' => '16:30:00',
                'slot' => 10,
                'gym_class_id' => 3,
            ],
            [
                'date' => Carbon::today()->addDays(3),
                'start_time' => '18:00:00',
                'end_time' => '19:00:00',
                'slot' => 10,
                'gym_class_id' => 3,
            ],
            [
                'date' => Carbon::today()->addDays(1),
                'start_time' => '09:00:00',
                'end_time' => '10:00:00',
                'slot' => 12,
                'gym_class_id' => 4,
            ],
            [
                'date' => Carbon::today()->addDays(1),
                'start_time' => '11:30:00',
                'end_time' => '12:30:00',
                'slot' => 12,
                'gym_class_id' => 4,
            ],
            [
                'date' => Carbon::today()->addDays(2),
                'start_time' => '08:00:00',
                'end_time' => '09:00:00',
                'slot' => 12,
                'gym_class_id' => 4,
            ],
            [
                'date' => Carbon::today()->addDays(2),
                'start_time' => '14:00:00',
                'end_time' => '15:00:00',
                'slot' => 12,
                'gym_class_id' => 4,
            ],
            [
                'date' => Carbon::today()->addDays(3),
                'start_time' => '16:00:00',
                'end_time' => '17:00:00',
                'slot' => 12,
                'gym_class_id' => 4,
            ],
            [
                'date' => Carbon::today()->addDays(1),
                'start_time' => '07:30:00',
                'end_time' => '08:30:00',
                'slot' => 18,
                'gym_class_id' => 5,
            ],
            [
                'date' => Carbon::today()->addDays(1),
                'start_time' => '10:15:00',
                'end_time' => '11:15:00',
                'slot' => 18,
                'gym_class_id' => 5,
            ],
            [
                'date' => Carbon::today()->addDays(2),
                'start_time' => '13:00:00',
                'end_time' => '14:00:00',
                'slot' => 18,
                'gym_class_id' => 5,
            ],
            [
                'date' => Carbon::today()->addDays(2),
                'start_time' => '15:30:00',
                'end_time' => '16:30:00',
                'slot' => 18,
                'gym_class_id' => 5,
            ],
            [
                'date' => Carbon::today()->addDays(3),
                'start_time' => '17:00:00',
                'end_time' => '18:00:00',
                'slot' => 18,
                'gym_class_id' => 5,
            ],
            [
                'date' => Carbon::today()->addDays(6),
                'start_time' => '13:00:00',
                'end_time' => '14:30:00',
                'slot' => 16,
                'gym_class_id' => 6,
            ],
            [
                'date' => Carbon::today()->addDays(7),
                'start_time' => '07:00:00',
                'end_time' => '08:00:00',
                'slot' => 10,
                'gym_class_id' => 7,
            ],
            [
                'date' => Carbon::today()->addDays(8),
                'start_time' => '16:00:00',
                'end_time' => '17:00:00',
                'slot' => 14,
                'gym_class_id' => 8,
            ],
            [
                'date' => Carbon::today()->addDays(9),
                'start_time' => '18:00:00',
                'end_time' => '19:00:00',
                'slot' => 20,
                'gym_class_id' => 9,
            ],
            [
                'date' => Carbon::today()->addDays(10),
                'start_time' => '11:00:00',
                'end_time' => '12:00:00',
                'slot' => 15,
                'gym_class_id' => 10,
            ],
            [
                'date' => Carbon::today()->addDays(11),
                'start_time' => '08:00:00',
                'end_time' => '09:30:00',
                'slot' => 18,
                'gym_class_id' => 11,
            ],
            [
                'date' => Carbon::today()->addDays(12),
                'start_time' => '12:00:00',
                'end_time' => '13:00:00',
                'slot' => 14,
                'gym_class_id' => 12,
            ],
            [
                'date' => Carbon::today()->addDays(13),
                'start_time' => '17:00:00',
                'end_time' => '18:30:00',
                'slot' => 20,
                'gym_class_id' => 13,
            ],
            [
                'date' => Carbon::today()->addDays(14),
                'start_time' => '06:00:00',
                'end_time' => '07:00:00',
                'slot' => 12,
                'gym_class_id' => 14,
            ],
            [
                'date' => Carbon::today()->addDays(15),
                'start_time' => '15:30:00',
                'end_time' => '16:30:00',
                'slot' => 10,
                'gym_class_id' => 15,
            ],
            [
                'date' => Carbon::today()->addDays(16),
                'start_time' => '10:00:00',
                'end_time' => '11:00:00',
                'slot' => 16,
                'gym_class_id' => 16,
            ],
            [
                'date' => Carbon::today()->addDays(17),
                'start_time' => '13:00:00',
                'end_time' => '14:00:00',
                'slot' => 8,
                'gym_class_id' => 17,
            ],
            [
                'date' => Carbon::today()->addDays(18),
                'start_time' => '16:00:00',
                'end_time' => '17:30:00',
                'slot' => 22,
                'gym_class_id' => 18,
            ],
            [
                'date' => Carbon::today()->addDays(19),
                'start_time' => '11:30:00',
                'end_time' => '12:30:00',
                'slot' => 13,
                'gym_class_id' => 19,
            ],
            [
                'date' => Carbon::today()->addDays(20),
                'start_time' => '09:00:00',
                'end_time' => '10:30:00',
                'slot' => 17,
                'gym_class_id' => 20,
            ],
            [
                'date' => Carbon::today()->addDays(21),
                'start_time' => '18:00:00',
                'end_time' => '19:30:00',
                'slot' => 19,
                'gym_class_id' => 21,
            ],
            [
                'date' => Carbon::today()->addDays(22),
                'start_time' => '07:00:00',
                'end_time' => '08:00:00',
                'slot' => 11,
                'gym_class_id' => 22,
            ],
            [
                'date' => Carbon::today()->addDays(23),
                'start_time' => '14:00:00',
                'end_time' => '15:30:00',
                'slot' => 21,
                'gym_class_id' => 23,
            ],
            [
                'date' => Carbon::today()->addDays(24),
                'start_time' => '12:30:00',
                'end_time' => '13:30:00',
                'slot' => 15,
                'gym_class_id' => 24,
            ],
            [
                'date' => Carbon::today()->addDays(25),
                'start_time' => '08:30:00',
                'end_time' => '10:00:00',
                'slot' => 20,
                'gym_class_id' => 25,
            ],
            [
                'date' => Carbon::today()->addDays(26),
                'start_time' => '15:00:00',
                'end_time' => '16:00:00',
                'slot' => 9,
                'gym_class_id' => 26,
            ],
            [
                'date' => Carbon::today()->addDays(27),
                'start_time' => '13:30:00',
                'end_time' => '14:30:00',
                'slot' => 12,
                'gym_class_id' => 27,
            ],
            [
                'date' => Carbon::today()->addDays(28),
                'start_time' => '17:30:00',
                'end_time' => '18:30:00',
                'slot' => 18,
                'gym_class_id' => 28,
            ],
            [
                'date' => Carbon::today()->addDays(29),
                'start_time' => '10:30:00',
                'end_time' => '11:30:00',
                'slot' => 14,
                'gym_class_id' => 29,
            ],
            [
                'date' => Carbon::today()->addDays(30),
                'start_time' => '07:30:00',
                'end_time' => '09:00:00',
                'slot' => 20,
                'gym_class_id' => 30,
            ]
        ];

        foreach ($schedules as $schedule) {
            GymClassSchedule::create($schedule);
        }
    }
}
