<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\PersonalTrainerPackage;

class PersonalTrainerPackageSeeder extends Seeder
{
    public function run(): void
    {
        $packages = [
            [
                'name' => 'Basic Fitness Coaching',
                'description' => 'Program dasar untuk pemula dalam kebugaran.',
                'day_duration' => 7,
                'price' => 300000,
                'images' => ['default.jpg'],
                'status' => 'active',
                'personal_trainer_id' => 1,
            ],
            [
                'name' => 'Weight Loss Program',
                'description' => 'Program personal trainer untuk penurunan berat badan.',
                'day_duration' => 14,
                'price' => 600000,
                'images' => ['default.jpg'],
                'status' => 'active',
                'personal_trainer_id' => 2,
            ],
            [
                'name' => 'Muscle Building Plan',
                'description' => 'Fokus pada pembentukan massa otot.',
                'day_duration' => 30,
                'price' => 1200000,
                'images' => ['default.jpg'],
                'status' => 'inactive',
                'personal_trainer_id' => 3,
            ],
            [
                'name' => 'Cardio Booster',
                'description' => 'Peningkatan stamina dan kebugaran jantung.',
                'day_duration' => 10,
                'price' => 400000,
                'images' => ['default.jpg'],
                'status' => 'active',
                'personal_trainer_id' => 1,
            ],
            [
                'name' => 'Post Injury Recovery',
                'description' => 'Pemulihan pasca cedera dengan pengawasan.',
                'day_duration' => 21,
                'price' => 900000,
                'images' => ['default.jpg'],
                'status' => 'inactive',
                'personal_trainer_id' => 2,
            ],
            [
                'name' => 'Strength Training',
                'description' => 'Latihan kekuatan intensif.',
                'day_duration' => 30,
                'price' => 1300000,
                'images' => ['default.jpg'],
                'status' => 'active',
                'personal_trainer_id' => 3,
            ],
            [
                'name' => 'Flexibility Training',
                'description' => 'Fokus pada fleksibilitas dan mobilitas.',
                'day_duration' => 10,
                'price' => 350000,
                'images' => ['default.jpg'],
                'status' => 'active',
                'personal_trainer_id' => 1,
            ],
            [
                'name' => 'Senior Fitness',
                'description' => 'Kebugaran untuk lansia.',
                'day_duration' => 15,
                'price' => 550000,
                'images' => ['default.jpg'],
                'status' => 'inactive',
                'personal_trainer_id' => 2,
            ],
            [
                'name' => 'Youth Sports Prep',
                'description' => 'Persiapan kompetisi olahraga untuk pelajar.',
                'day_duration' => 20,
                'price' => 800000,
                'images' => ['default.jpg'],
                'status' => 'active',
                'personal_trainer_id' => 3,
            ],
            [
                'name' => 'Prenatal Fitness',
                'description' => 'Program untuk ibu hamil.',
                'day_duration' => 14,
                'price' => 650000,
                'images' => ['default.jpg'],
                'status' => 'active',
                'personal_trainer_id' => 1,
            ],
            [
                'name' => 'Functional Training',
                'description' => 'Gerakan yang meniru aktivitas sehari-hari.',
                'day_duration' => 12,
                'price' => 500000,
                'images' => ['default.jpg'],
                'status' => 'active',
                'personal_trainer_id' => 2,
            ],
            [
                'name' => 'Endurance Challenge',
                'description' => 'Meningkatkan daya tahan tubuh.',
                'day_duration' => 30,
                'price' => 1100000,
                'images' => ['default.jpg'],
                'status' => 'inactive',
                'personal_trainer_id' => 3,
            ],
            [
                'name' => 'Core Stability',
                'description' => 'Latihan untuk otot inti.',
                'day_duration' => 14,
                'price' => 600000,
                'images' => ['default.jpg'],
                'status' => 'active',
                'personal_trainer_id' => 1,
            ],
            [
                'name' => 'Agility Training',
                'description' => 'Meningkatkan kecepatan dan kelincahan.',
                'day_duration' => 10,
                'price' => 400000,
                'images' => ['default.jpg'],
                'status' => 'inactive',
                'personal_trainer_id' => 2,
            ],
            [
                'name' => 'Rehab Therapy',
                'description' => 'Pemulihan pasca operasi.',
                'day_duration' => 20,
                'price' => 1000000,
                'images' => ['default.jpg'],
                'status' => 'active',
                'personal_trainer_id' => 3,
            ],
            [
                'name' => 'Total Body Workout',
                'description' => 'Program menyeluruh untuk tubuh.',
                'day_duration' => 15,
                'price' => 750000,
                'images' => ['default.jpg'],
                'status' => 'active',
                'personal_trainer_id' => 1,
            ],
            [
                'name' => 'Bootcamp Intensive',
                'description' => 'Latihan militer-style intens.',
                'day_duration' => 7,
                'price' => 450000,
                'images' => ['default.jpg'],
                'status' => 'active',
                'personal_trainer_id' => 2,
            ],
            [
                'name' => 'Morning Energizer',
                'description' => 'Latihan pagi hari untuk memulai hari.',
                'day_duration' => 5,
                'price' => 250000,
                'images' => ['default.jpg'],
                'status' => 'inactive',
                'personal_trainer_id' => 3,
            ],
            [
                'name' => 'Evening Relaxation',
                'description' => 'Latihan ringan untuk sore/malam.',
                'day_duration' => 10,
                'price' => 400000,
                'images' => ['default.jpg'],
                'status' => 'active',
                'personal_trainer_id' => 1,
            ],
            [
                'name' => 'Weekend Warrior',
                'description' => 'Khusus akhir pekan.',
                'day_duration' => 2,
                'price' => 150000,
                'images' => ['default.jpg'],
                'status' => 'active',
                'personal_trainer_id' => 2,
            ],
            
            [
                'name' => 'Beginner Bootcamp', 
                'description' => 'Bootcamp untuk pemula.', 
                'day_duration' => 7, 
                'price' => 300000, 
                'images' => ['default.jpg'], 
                'status' => 'active', 
                'personal_trainer_id' => 3,
            ],
            [
                'name' => 'Advanced HIIT', 
                'description' => 'HIIT tingkat lanjut.', 
                'day_duration' => 14, 
                'price' => 650000, 
                'images' => ['default.jpg'], 
                'status' => 'inactive', 
                'personal_trainer_id' => 1,
            ],
            [
                'name' => 'Outdoor Training', 
                'description' => 'Latihan di luar ruangan.', 
                'day_duration' => 10, 
                'price' => 500000, 
                'images' => ['default.jpg'], 
                'status' => 'active', 
                'personal_trainer_id' => 2,
            ],
            [
                'name' => 'Indoor Cycling', 
                'description' => 'Kelas sepeda dalam ruangan.', 
                'day_duration' => 15, 
                'price' => 600000, 
                'images' => ['default.jpg'], 
                'status' => 'active', 
                'personal_trainer_id' => 3,
            ],
            [
                'name' => 'Speed & Power', 
                'description' => 'Fokus pada kecepatan dan kekuatan.', 
                'day_duration' => 20, 
                'price' => 850000, 
                'images' => ['default.jpg'], 
                'status' => 'inactive', 
                'personal_trainer_id' => 1,
            ],
            [
                'name' => 'Glute & Leg Day', 
                'description' => 'Khusus otot kaki dan glute.', 
                'day_duration' => 12, 
                'price' => 450000, 
                'images' => ['default.jpg'], 
                'status' => 'active', 
                'personal_trainer_id' => 2,
            ],
            [
                'name' => 'Athlete Training', 
                'description' => 'Latihan untuk atlet.', 
                'day_duration' => 30, 
                'price' => 1500000, 
                'images' => ['default.jpg'], 
                'status' => 'active', 
                'personal_trainer_id' => 3,
            ],
            [
                'name' => 'Fat Burner Express', 
                'description' => 'Program cepat pembakaran lemak.', 
                'day_duration' => 7, 
                'price' => 400000, 
                'images' => ['default.jpg'], 
                'status' => 'inactive', 
                'personal_trainer_id' => 1,
            ],
            [
                'name' => 'Stretch & Recovery', 
                'description' => 'Program relaksasi dan peregangan.', 
                'day_duration' => 10, 
                'price' => 500000, 
                'images' => ['default.jpg'], 
                'status' => 'active', 
                'personal_trainer_id' => 2,
            ],
            [
                'name' => 'Balance & Coordination', 
                'description' => 'Meningkatkan keseimbangan.', 
                'day_duration' => 15, 
                'price' => 700000, 
                'images' => ['default.jpg'], 
                'status' => 'active', 
                'personal_trainer_id' => 3,
            ],
        ];

        foreach ($packages as $package) {
            PersonalTrainerPackage::create($package);
        }
    }
}
