<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\PersonalTrainerPackage;

class PersonalTrainerPackageSeeder extends Seeder
{
    public function run(): void
    {
        $packages = [
            [
                'name' => 'Basic Fitness Coaching',
                'description' => 'Program dasar untuk pemula dalam kebugaran.',
                'day_duration' => 7,
                'price' => 300000,
                'images' => ['personal_trainer_package\/ptp1.jpg'],
                'status' => 'active',
                'personal_trainer_id' => 1,
            ],
            [
                'name' => 'Weight Loss Program',
                'description' => 'Program personal trainer untuk penurunan berat badan.',
                'day_duration' => 14,
                'price' => 600000,
                'images' => ['personal_trainer_package\/ptp2.jpg'],
                'status' => 'active',
                'personal_trainer_id' => 9,
            ],
            [
                'name' => 'Muscle Building Plan',
                'description' => 'Fokus pada pembentukan massa otot.',
                'day_duration' => 30,
                'price' => 1200000,
                'images' => ['personal_trainer_package\/ptp3.jpg'],
                'status' => 'inactive',
                'personal_trainer_id' => 3,
            ],
            [
                'name' => 'Cardio Booster',
                'description' => 'Peningkatan stamina dan kebugaran jantung.',
                'day_duration' => 10,
                'price' => 400000,
                'images' => ['personal_trainer_package\/ptp4.jpg'],
                'status' => 'active',
                'personal_trainer_id' => 2,
            ],
            [
                'name' => 'Post Injury Recovery',
                'description' => 'Pemulihan pasca cedera dengan pengawasan.',
                'day_duration' => 21,
                'price' => 900000,
                'images' => ['personal_trainer_package\/ptp5.jpg'],
                'status' => 'inactive',
                'personal_trainer_id' => 2,
            ],
            [
                'name' => 'Strength Training',
                'description' => 'Latihan kekuatan intensif.',
                'day_duration' => 30,
                'price' => 1300000,
                'images' => ['personal_trainer_package\/ptp6.jpg'],
                'status' => 'active',
                'personal_trainer_id' => 3,
            ],
            [
                'name' => 'Flexibility Training',
                'description' => 'Fokus pada fleksibilitas dan mobilitas.',
                'day_duration' => 10,
                'price' => 350000,
                'images' => ['personal_trainer_package\/ptp7.jpg'],
                'status' => 'active',
                'personal_trainer_id' => 2,
            ],
            [
                'name' => 'Senior Fitness',
                'description' => 'Kebugaran untuk lansia.',
                'day_duration' => 15,
                'price' => 550000,
                'images' => ['personal_trainer_package\/ptp8.jpg'],
                'status' => 'inactive',
                'personal_trainer_id' => 3,
            ],
            [
                'name' => 'Youth Sports Prep',
                'description' => 'Persiapan kompetisi olahraga untuk pelajar.',
                'day_duration' => 20,
                'price' => 800000,
                'images' => ['personal_trainer_package\/ptp9.jpg'],
                'status' => 'active',
                'personal_trainer_id' => 6,
            ],
            [
                'name' => 'Prenatal Fitness',
                'description' => 'Program untuk ibu hamil.',
                'day_duration' => 14,
                'price' => 650000,
                'images' => ['personal_trainer_package\/ptp10.jpg'],
                'status' => 'active',
                'personal_trainer_id' => 1,
            ],
            [
                'name' => 'Functional Training',
                'description' => 'Gerakan yang meniru aktivitas sehari-hari.',
                'day_duration' => 12,
                'price' => 500000,
                'images' => ['personal_trainer_package\/ptp11.jpg'],
                'status' => 'active',
                'personal_trainer_id' => 4,
            ],
            [
                'name' => 'Endurance Challenge',
                'description' => 'Meningkatkan daya tahan tubuh.',
                'day_duration' => 30,
                'price' => 1100000,
                'images' => ['personal_trainer_package\/ptp12.jpg'],
                'status' => 'inactive',
                'personal_trainer_id' => 8,
            ],
            [
                'name' => 'Agility Training',
                'description' => 'Meningkatkan kecepatan dan kelincahan.',
                'day_duration' => 10,
                'price' => 400000,
                'images' => ['personal_trainer_package\/ptp13.jpg'],
                'status' => 'inactive',
                'personal_trainer_id' => 2,
            ],
            [
                'name' => 'Rehab Therapy',
                'description' => 'Pemulihan pasca operasi.',
                'day_duration' => 20,
                'price' => 1000000,
                'images' => ['personal_trainer_package\/ptp14.jpg'],
                'status' => 'active',
                'personal_trainer_id' => 1,
            ],
            [
                'name' => 'Total Body Workout',
                'description' => 'Program menyeluruh untuk tubuh.',
                'day_duration' => 15,
                'price' => 750000,
                'images' => ['personal_trainer_package\/ptp15.jpg'],
                'status' => 'active',
                'personal_trainer_id' => 1,
            ],
            [
                'name' => 'Bootcamp Intensive',
                'description' => 'Latihan militer-style intens.',
                'day_duration' => 7,
                'price' => 450000,
                'images' => ['personal_trainer_package\/ptp16.jpg'],
                'status' => 'active',
                'personal_trainer_id' => 7,
            ],
            [
                'name' => 'Morning Energizer',
                'description' => 'Latihan pagi hari untuk memulai hari.',
                'day_duration' => 5,
                'price' => 250000,
                'images' => ['personal_trainer_package\/ptp17.jpg'],
                'status' => 'inactive',
                'personal_trainer_id' => 3,
            ],
            [
                'name' => 'Evening Relaxation',
                'description' => 'Latihan ringan untuk sore/malam.',
                'day_duration' => 10,
                'price' => 400000,
                'images' => ['personal_trainer_package\/ptp18.jpg'],
                'status' => 'active',
                'personal_trainer_id' => 1,
            ],
            [
                'name' => 'Weekend Warrior',
                'description' => 'Khusus akhir pekan.',
                'day_duration' => 2,
                'price' => 150000,
                'images' => ['personal_trainer_package\/ptp19.jpg'],
                'status' => 'active',
                'personal_trainer_id' => 2,
            ],

            [
                'name' => 'Beginner Bootcamp',
                'description' => 'Bootcamp untuk pemula.',
                'day_duration' => 7,
                'price' => 300000,
                'images' => ['personal_trainer_package\/ptp20.jpg'],
                'status' => 'active',
                'personal_trainer_id' => 3,
            ],
            [
                'name' => 'Advanced HIIT',
                'description' => 'HIIT tingkat lanjut.',
                'day_duration' => 14,
                'price' => 650000,
                'images' => ['personal_trainer_package\/ptp21.jpg'],
                'status' => 'inactive',
                'personal_trainer_id' => 4,
            ],
            [
                'name' => 'Speed & Power',
                'description' => 'Fokus pada kecepatan dan kekuatan.',
                'day_duration' => 20,
                'price' => 850000,
                'images' => ['personal_trainer_package\/ptp22.jpg'],
                'status' => 'inactive',
                'personal_trainer_id' => 5,
            ],
            [
                'name' => 'Athlete Training',
                'description' => 'Latihan untuk atlet.',
                'day_duration' => 30,
                'price' => 1500000,
                'images' => ['personal_trainer_package\/ptp23.jpg'],
                'status' => 'active',
                'personal_trainer_id' => 5,
            ],
            [
                'name' => 'Fat Burner Express',
                'description' => 'Program cepat pembakaran lemak.',
                'day_duration' => 7,
                'price' => 400000,
                'images' => ['personal_trainer_package\/ptp24.jpg'],
                'status' => 'inactive',
                'personal_trainer_id' => 9,
            ],
            
        ];

        foreach ($packages as $package) {
            PersonalTrainerPackage::create($package);
        }
    }
}
