<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    public function run(): void
    {
        $users = [
            // 2 Admin
            [
                'name' => 'Admin One',
                'email' => 'admin@example.com',
                'password' => Hash::make('qwerty123'),
                'email_verified_at' => now(),
                'role' => 'admin',
                'membership_registered' => 'registered',
                'membership_status' => 'inactive',
                'membership_end_date' => now()->addYear(),
                'profile_bio' => 'Primary system administrator.',
                'profile_image' => 'user_profile\/default-user_profile.jpg',
            ],
            [
                'name' => 'Admin Two',
                'email' => 'admin2@example.com',
                'password' => Hash::make('qwerty123'),
                'email_verified_at' => now(),
                'role' => 'admin',
                'membership_registered' => 'registered',
                'membership_status' => 'active',
                'membership_end_date' => now()->addYear(),
                'profile_bio' => 'Backup system administrator.',
                'profile_image' => 'user_profile\/default-user_profile.jpg',
            ],

            // 25 Trainer

            [
                'name' => 'Athallah',
                'email' => 'trainer@example.com',
                'password' => Hash::make('qwerty123'),
                'email_verified_at' => now(),
                'role' => 'trainer',
                'membership_registered' => 'registered',
                'membership_status' => 'active',
                'membership_end_date' => now()->addMonths(6),
                'profile_bio' => 'Spesialis dalam pembentukan otot dan nutrisi.',
                'profile_image' => 'user_profile\/default-user_profile.jpg',
            ],
            [
                'name' => 'Trainer Two',
                'email' => 'trainer2@example.com',
                'password' => Hash::make('qwerty123'),
                'email_verified_at' => now(),
                'role' => 'trainer',
                'membership_registered' => 'registered',
                'membership_status' => 'active',
                'membership_end_date' => now()->addMonths(6),
                'profile_bio' => 'Berpengalaman melatih atlet remaja.',
                'profile_image' => 'user_profile\/default-user_profile.jpg',
            ],
            [
                'name' => 'Trainer Three',
                'email' => 'trainer3@example.com',
                'password' => Hash::make('qwerty123'),
                'email_verified_at' => now(),
                'role' => 'trainer',
                'membership_registered' => 'registered',
                'membership_status' => 'active',
                'membership_end_date' => now()->addMonths(6),
                'profile_bio' => 'Ahli dalam latihan fungsional dan mobilitas.',
                'profile_image' => 'user_profile\/default-user_profile.jpg',
            ],
            [
                'name' => 'Trainer Four',
                'email' => 'trainer4@example.com',
                'password' => Hash::make('qwerty123'),
                'email_verified_at' => now(),
                'role' => 'trainer',
                'membership_registered' => 'registered',
                'membership_status' => 'active',
                'membership_end_date' => now()->addMonths(6),
                'profile_bio' => 'Pelatih HIIT dan cardio tingkat lanjut.',
                'profile_image' => 'user_profile\/default-user_profile.jpg',
            ],
            [
                'name' => 'Trainer Five',
                'email' => 'trainer5@example.com',
                'password' => Hash::make('qwerty123'),
                'email_verified_at' => now(),
                'role' => 'trainer',
                'membership_registered' => 'registered',
                'membership_status' => 'active',
                'membership_end_date' => now()->addMonths(6),
                'profile_bio' => 'Pelatih kebugaran umum.',
                'profile_image' => 'user_profile\/default-user_profile.jpg',
            ],
            [
                'name' => 'Trainer Six',
                'email' => 'trainer6@example.com',
                'password' => Hash::make('qwerty123'),
                'email_verified_at' => now(),
                'role' => 'trainer',
                'membership_registered' => 'registered',
                'membership_status' => 'active',
                'membership_end_date' => now()->addMonths(6),
                'profile_bio' => 'Berfokus pada kebugaran wanita.',
                'profile_image' => 'user_profile\/default-user_profile.jpg',
            ],
            [
                'name' => 'Trainer Seven',
                'email' => 'trainer7@example.com',
                'password' => Hash::make('qwerty123'),
                'email_verified_at' => now(),
                'role' => 'trainer',
                'membership_registered' => 'registered',
                'membership_status' => 'active',
                'membership_end_date' => now()->addMonths(6),
                'profile_bio' => 'Ahli rehabilitasi cedera olahraga.',
                'profile_image' => 'user_profile\/default-user_profile.jpg',
            ],
            [
                'name' => 'Trainer Eight',
                'email' => 'trainer8@example.com',
                'password' => Hash::make('qwerty123'),
                'email_verified_at' => now(),
                'role' => 'trainer',
                'membership_registered' => 'registered',
                'membership_status' => 'active',
                'membership_end_date' => now()->addMonths(6),
                'profile_bio' => 'Spesialis stretching dan fleksibilitas.',
                'profile_image' => 'user_profile\/default-user_profile.jpg',
            ],
            [
                'name' => 'Trainer Nine',
                'email' => 'trainer9@example.com',
                'password' => Hash::make('qwerty123'),
                'email_verified_at' => now(),
                'role' => 'trainer',
                'membership_registered' => 'registered',
                'membership_status' => 'active',
                'membership_end_date' => now()->addMonths(6),
                'profile_bio' => 'Berpengalaman dalam pelatihan lansia.',
                'profile_image' => 'user_profile\/default-user_profile.jpg',
            ],
            [
                'name' => 'Trainer Ten',
                'email' => 'trainer10@example.com',
                'password' => Hash::make('qwerty123'),
                'email_verified_at' => now(),
                'role' => 'trainer',
                'membership_registered' => 'registered',
                'membership_status' => 'active',
                'membership_end_date' => now()->addMonths(6),
                'profile_bio' => 'Pelatih fitness outdoor dan hiking.',
                'profile_image' => 'user_profile\/default-user_profile.jpg',
            ],
            [
                'name' => 'Trainer Eleven',
                'email' => 'trainer11@example.com',
                'password' => Hash::make('qwerty123'),
                'email_verified_at' => now(),
                'role' => 'trainer',
                'membership_registered' => 'registered',
                'membership_status' => 'active',
                'membership_end_date' => now()->addMonths(6),
                'profile_bio' => 'Instruktur zumba dan aerobik.',
                'profile_image' => 'user_profile\/default-user_profile.jpg',
            ],
            [
                'name' => 'Trainer Twelve',
                'email' => 'trainer12@example.com',
                'password' => Hash::make('qwerty123'),
                'email_verified_at' => now(),
                'role' => 'trainer',
                'membership_registered' => 'registered',
                'membership_status' => 'active',
                'membership_end_date' => now()->addMonths(6),
                'profile_bio' => 'Pakar olahraga untuk penurunan berat badan.',
                'profile_image' => 'user_profile\/default-user_profile.jpg',
            ],
            [
                'name' => 'Trainer Thirteen',
                'email' => 'trainer13@example.com',
                'password' => Hash::make('qwerty123'),
                'email_verified_at' => now(),
                'role' => 'trainer',
                'membership_registered' => 'registered',
                'membership_status' => 'active',
                'membership_end_date' => now()->addMonths(6),
                'profile_bio' => 'Pelatih tinju dan bela diri dasar.',
                'profile_image' => 'user_profile\/default-user_profile.jpg',
            ],
            [
                'name' => 'Trainer Fourteen',
                'email' => 'trainer14@example.com',
                'password' => Hash::make('qwerty123'),
                'email_verified_at' => now(),
                'role' => 'trainer',
                'membership_registered' => 'registered',
                'membership_status' => 'active',
                'membership_end_date' => now()->addMonths(6),
                'profile_bio' => 'Mendalami yoga dan mindfulness fitness.',
                'profile_image' => 'user_profile\/default-user_profile.jpg',
            ],
            [
                'name' => 'Trainer Fifteen',
                'email' => 'trainer15@example.com',
                'password' => Hash::make('qwerty123'),
                'email_verified_at' => now(),
                'role' => 'trainer',
                'membership_registered' => 'registered',
                'membership_status' => 'active',
                'membership_end_date' => now()->addMonths(6),
                'profile_bio' => 'Fokus pada pelatihan speed dan agility.',
                'profile_image' => 'user_profile\/default-user_profile.jpg',
            ],
            [
                'name' => 'Trainer Sixteen',
                'email' => 'trainer16@example.com',
                'password' => Hash::make('qwerty123'),
                'email_verified_at' => now(),
                'role' => 'trainer',
                'membership_registered' => 'registered',
                'membership_status' => 'active',
                'membership_end_date' => now()->addMonths(6),
                'profile_bio' => 'Pelatih TRX dan bodyweight training.',
                'profile_image' => 'user_profile\/default-user_profile.jpg',
            ],
            [
                'name' => 'Trainer Seventeen',
                'email' => 'trainer17@example.com',
                'password' => Hash::make('qwerty123'),
                'email_verified_at' => now(),
                'role' => 'trainer',
                'membership_registered' => 'registered',
                'membership_status' => 'active',
                'membership_end_date' => now()->addMonths(6),
                'profile_bio' => 'Ahli postur tubuh dan koreksi gerakan.',
                'profile_image' => 'user_profile\/default-user_profile.jpg',
            ],
            [
                'name' => 'Trainer Eighteen',
                'email' => 'trainer18@example.com',
                'password' => Hash::make('qwerty123'),
                'email_verified_at' => now(),
                'role' => 'trainer',
                'membership_registered' => 'registered',
                'membership_status' => 'active',
                'membership_end_date' => now()->addMonths(6),
                'profile_bio' => 'Pelatih anak-anak dan remaja aktif.',
                'profile_image' => 'user_profile\/default-user_profile.jpg',
            ],
            [
                'name' => 'Trainer Nineteen',
                'email' => 'trainer19@example.com',
                'password' => Hash::make('qwerty123'),
                'email_verified_at' => now(),
                'role' => 'trainer',
                'membership_registered' => 'registered',
                'membership_status' => 'active',
                'membership_end_date' => now()->addMonths(6),
                'profile_bio' => 'Menggabungkan latihan fisik dengan nutrisi.',
                'profile_image' => 'user_profile\/default-user_profile.jpg',
            ],
            [
                'name' => 'Trainer Twenty',
                'email' => 'trainer20@example.com',
                'password' => Hash::make('qwerty123'),
                'email_verified_at' => now(),
                'role' => 'trainer',
                'membership_registered' => 'registered',
                'membership_status' => 'active',
                'membership_end_date' => now()->addMonths(6),
                'profile_bio' => 'Spesialis crossfit dan endurance.',
                'profile_image' => 'user_profile\/default-user_profile.jpg',
            ],
            [
                'name' => 'Trainer Twenty-One',
                'email' => 'trainer21@example.com',
                'password' => Hash::make('qwerty123'),
                'email_verified_at' => now(),
                'role' => 'trainer',
                'membership_registered' => 'registered',
                'membership_status' => 'active',
                'membership_end_date' => now()->addMonths(6),
                'profile_bio' => 'Berpengalaman 10 tahun di dunia fitness.',
                'profile_image' => 'user_profile\/default-user_profile.jpg',
            ],
            [
                'name' => 'Trainer Twenty-Two',
                'email' => 'trainer22@example.com',
                'password' => Hash::make('qwerty123'),
                'email_verified_at' => now(),
                'role' => 'trainer',
                'membership_registered' => 'registered',
                'membership_status' => 'active',
                'membership_end_date' => now()->addMonths(6),
                'profile_bio' => 'Fokus pada latihan fungsional untuk keseharian.',
                'profile_image' => 'user_profile\/default-user_profile.jpg',
            ],
            [
                'name' => 'Trainer Twenty-Three',
                'email' => 'trainer23@example.com',
                'password' => Hash::make('qwerty123'),
                'email_verified_at' => now(),
                'role' => 'trainer',
                'membership_registered' => 'registered',
                'membership_status' => 'active',
                'membership_end_date' => now()->addMonths(6),
                'profile_bio' => 'Spesialis olahraga air dan pelatihan renang.',
                'profile_image' => 'user_profile\/default-user_profile.jpg',
            ],
            [
                'name' => 'Trainer Twenty-Four',
                'email' => 'trainer24@example.com',
                'password' => Hash::make('qwerty123'),
                'email_verified_at' => now(),
                'role' => 'trainer',
                'membership_registered' => 'registered',
                'membership_status' => 'active',
                'membership_end_date' => now()->addMonths(6),
                'profile_bio' => 'Menggabungkan metode barbell dan calisthenics.',
                'profile_image' => 'user_profile\/default-user_profile.jpg',
            ],
            [
                'name' => 'Trainer Twenty-Five',
                'email' => 'trainer25@example.com',
                'password' => Hash::make('qwerty123'),
                'email_verified_at' => now(),
                'role' => 'trainer',
                'membership_registered' => 'registered',
                'membership_status' => 'active',
                'membership_end_date' => now()->addMonths(6),
                'profile_bio' => 'Ahli motivasi olahraga dan pembentukan kebiasaan.',
                'profile_image' => 'user_profile\/default-user_profile.jpg',
            ],



            // 25 Member
             [
                'name' => 'Supri',
                'email' => 'member@example.com',
                'password' => Hash::make('qwerty123'),
                'email_verified_at' => now(),
                'role' => 'member',
                'membership_registered' => 'registered',
                'membership_status' => 'inactive',
                'membership_end_date' => now()->addDays(135),
                'profile_bio' => 'Aktif mengikuti kelas zumba.',
                'profile_image' => 'user_profile\/m1.jpg',
            ],
            [
                'name' => 'Member 2',
                'email' => 'member2@example.com',
                'password' => Hash::make('qwerty123'),
                'email_verified_at' => now(),
                'role' => 'member',
                'membership_registered' => 'unregistered',
                'membership_status' => 'inactive',
                'membership_end_date' => now()->addDays(43),
                'profile_bio' => 'Menggemari latihan kardio.',
                'profile_image' => 'user_profile\/default-user_profile.jpg',
            ],
            [
                'name' => 'Member 3',
                'email' => 'member3@example.com',
                'password' => Hash::make('qwerty123'),
                'email_verified_at' => now(),
                'role' => 'member',
                'membership_registered' => 'registered',
                'membership_status' => 'inactive',
                'membership_end_date' => now()->addDays(102),
                'profile_bio' => 'Sering hadir di akhir pekan.',
                'profile_image' => 'user_profile\/default-user_profile.jpg',
            ],
            [
                'name' => 'Member 4',
                'email' => 'member4@example.com',
                'password' => Hash::make('qwerty123'),
                'email_verified_at' => now(),
                'role' => 'member',
                'membership_registered' => 'unregistered',
                'membership_status' => 'inactive',
                'membership_end_date' => now()->addDays(60),
                'profile_bio' => 'Berpartisipasi dalam lomba kebugaran.',
                'profile_image' => 'user_profile\/default-user_profile.jpg',
            ],
            [
                'name' => 'Member 5',
                'email' => 'member5@example.com',
                'password' => Hash::make('qwerty123'),
                'email_verified_at' => now(),
                'role' => 'member',
                'membership_registered' => 'unregistered',
                'membership_status' => 'active',
                'membership_end_date' => now()->addDays(170),
                'profile_bio' => 'Fokus pada diet sehat.',
                'profile_image' => 'user_profile\/default-user_profile.jpg',
            ],
            [
                'name' => 'Member 6',
                'email' => 'member6@example.com',
                'password' => Hash::make('qwerty123'),
                'email_verified_at' => now(),
                'role' => 'member',
                'membership_registered' => 'registered',
                'membership_status' => 'active',
                'membership_end_date' => now()->addDays(80),
                'profile_bio' => 'Senang berlatih angkat beban.',
                'profile_image' => 'user_profile\/default-user_profile.jpg',
            ],
            [
                'name' => 'Member 7',
                'email' => 'member7@example.com',
                'password' => Hash::make('qwerty123'),
                'email_verified_at' => now(),
                'role' => 'member',
                'membership_registered' => 'registered',
                'membership_status' => 'active',
                'membership_end_date' => now()->addDays(50),
                'profile_bio' => 'Mengikuti kelas HIIT setiap minggu.',
                'profile_image' => 'user_profile\/default-user_profile.jpg',
            ],
            [
                'name' => 'Member 8',
                'email' => 'member8@example.com',
                'password' => Hash::make('qwerty123'),
                'email_verified_at' => now(),
                'role' => 'member',
                'membership_registered' => 'unregistered',
                'membership_status' => 'inactive',
                'membership_end_date' => now()->addDays(30),
                'profile_bio' => 'Baru memulai latihan gym.',
                'profile_image' => 'user_profile\/default-user_profile.jpg',
            ],
            [
                'name' => 'Member 9',
                'email' => 'member9@example.com',
                'password' => Hash::make('qwerty123'),
                'email_verified_at' => now(),
                'role' => 'member',
                'membership_registered' => 'registered',
                'membership_status' => 'inactive',
                'membership_end_date' => now()->addDays(120),
                'profile_bio' => 'Meminati kelas pilates.',
                'profile_image' => 'user_profile\/default-user_profile.jpg',
            ],
            [
                'name' => 'Member 10',
                'email' => 'member10@example.com',
                'password' => Hash::make('qwerty123'),
                'email_verified_at' => now(),
                'role' => 'member',
                'membership_registered' => 'unregistered',
                'membership_status' => 'active',
                'membership_end_date' => now()->addDays(90),
                'profile_bio' => 'Selalu aktif dalam kegiatan komunitas gym.',
                'profile_image' => 'user_profile\/default-user_profile.jpg',
            ],
            [
                'name' => 'Member 11',
                'email' => 'member11@example.com',
                'password' => Hash::make('qwerty123'),
                'email_verified_at' => now(),
                'role' => 'member',
                'membership_registered' => 'registered',
                'membership_status' => 'active',
                'membership_end_date' => now()->addDays(45),
                'profile_bio' => 'Memiliki tujuan menurunkan berat badan.',
                'profile_image' => 'user_profile\/default-user_profile.jpg',
            ],
            [
                'name' => 'Member 12',
                'email' => 'member12@example.com',
                'password' => Hash::make('qwerty123'),
                'email_verified_at' => now(),
                'role' => 'member',
                'membership_registered' => 'registered',
                'membership_status' => 'active',
                'membership_end_date' => now()->addDays(180),
                'profile_bio' => 'Penggemar senam aerobik.',
                'profile_image' => 'user_profile\/default-user_profile.jpg',
            ],
            [
                'name' => 'Member 13',
                'email' => 'member13@example.com',
                'password' => Hash::make('qwerty123'),
                'email_verified_at' => now(),
                'role' => 'member',
                'membership_registered' => 'unregistered',
                'membership_status' => 'inactive',
                'membership_end_date' => now()->addDays(20),
                'profile_bio' => 'Sering berlatih dengan pelatih pribadi.',
                'profile_image' => 'user_profile\/default-user_profile.jpg',
            ],
            [
                'name' => 'Member 14',
                'email' => 'member14@example.com',
                'password' => Hash::make('qwerty123'),
                'email_verified_at' => now(),
                'role' => 'member',
                'membership_registered' => 'unregistered',
                'membership_status' => 'inactive',
                'membership_end_date' => now()->addDays(25),
                'profile_bio' => 'Lebih suka latihan mandiri.',
                'profile_image' => 'user_profile\/default-user_profile.jpg',
            ],
            [
                'name' => 'Member 15',
                'email' => 'member15@example.com',
                'password' => Hash::make('qwerty123'),
                'email_verified_at' => now(),
                'role' => 'member',
                'membership_registered' => 'registered',
                'membership_status' => 'inactive',
                'membership_end_date' => now()->addDays(60),
                'profile_bio' => 'Suka berolahraga malam hari.',
                'profile_image' => 'user_profile\/default-user_profile.jpg',
            ],
            [
                'name' => 'Member 16',
                'email' => 'member16@example.com',
                'password' => Hash::make('qwerty123'),
                'email_verified_at' => now(),
                'role' => 'member',
                'membership_registered' => 'registered',
                'membership_status' => 'active',
                'membership_end_date' => now()->addDays(130),
                'profile_bio' => 'Menikmati suasana gym yang santai.',
                'profile_image' => 'user_profile\/default-user_profile.jpg',
            ],
            [
                'name' => 'Member 17',
                'email' => 'member17@example.com',
                'password' => Hash::make('qwerty123'),
                'email_verified_at' => now(),
                'role' => 'member',
                'membership_registered' => 'unregistered',
                'membership_status' => 'active',
                'membership_end_date' => now()->addDays(150),
                'profile_bio' => 'Biasa mengikuti sesi pagi.',
                'profile_image' => 'user_profile\/default-user_profile.jpg',
            ],
            [
                'name' => 'Member 18',
                'email' => 'member18@example.com',
                'password' => Hash::make('qwerty123'),
                'email_verified_at' => now(),
                'role' => 'member',
                'membership_registered' => 'registered',
                'membership_status' => 'inactive',
                'membership_end_date' => now()->addDays(75),
                'profile_bio' => 'Baru pulih dari cedera.',
                'profile_image' => 'user_profile\/default-user_profile.jpg',
            ],
            [
                'name' => 'Member 19',
                'email' => 'member19@example.com',
                'password' => Hash::make('qwerty123'),
                'email_verified_at' => now(),
                'role' => 'member',
                'membership_registered' => 'registered',
                'membership_status' => 'active',
                'membership_end_date' => now()->addDays(200),
                'profile_bio' => 'Terdaftar dalam program pelatihan pribadi.',
                'profile_image' => 'user_profile\/default-user_profile.jpg',
            ],
            [
                'name' => 'Member 20',
                'email' => 'member20@example.com',
                'password' => Hash::make('qwerty123'),
                'email_verified_at' => now(),
                'role' => 'member',
                'membership_registered' => 'unregistered',
                'membership_status' => 'inactive',
                'membership_end_date' => now()->addDays(40),
                'profile_bio' => 'Fokus pada kekuatan otot inti.',
                'profile_image' => 'user_profile\/default-user_profile.jpg',
            ],
            [
                'name' => 'Member 21',
                'email' => 'member21@example.com',
                'password' => Hash::make('qwerty123'),
                'email_verified_at' => now(),
                'role' => 'member',
                'membership_registered' => 'registered',
                'membership_status' => 'inactive',
                'membership_end_date' => now()->addDays(15),
                'profile_bio' => 'Berlatih 3 kali seminggu.',
                'profile_image' => 'user_profile\/default-user_profile.jpg',
            ],
            [
                'name' => 'Member 22',
                'email' => 'member22@example.com',
                'password' => Hash::make('qwerty123'),
                'email_verified_at' => now(),
                'role' => 'member',
                'membership_registered' => 'unregistered',
                'membership_status' => 'active',
                'membership_end_date' => now()->addDays(100),
                'profile_bio' => 'Mengikuti semua kelas yoga.',
                'profile_image' => 'user_profile\/default-user_profile.jpg',
            ],
            [
                'name' => 'Member 23',
                'email' => 'member23@example.com',
                'password' => Hash::make('qwerty123'),
                'email_verified_at' => now(),
                'role' => 'member',
                'membership_registered' => 'registered',
                'membership_status' => 'inactive',
                'membership_end_date' => now()->addDays(10),
                'profile_bio' => 'Lebih nyaman berolahraga sendiri.',
                'profile_image' => 'user_profile\/default-user_profile.jpg',
            ],
            [
                'name' => 'Member 24',
                'email' => 'member24@example.com',
                'password' => Hash::make('qwerty123'),
                'email_verified_at' => now(),
                'role' => 'member',
                'membership_registered' => 'unregistered',
                'membership_status' => 'active',
                'membership_end_date' => now()->addDays(210),
                'profile_bio' => 'Suka tantangan olahraga intensif.',
                'profile_image' => 'user_profile\/default-user_profile.jpg',
            ],
            [
                'name' => 'Member 25',
                'email' => 'member25@example.com',
                'password' => Hash::make('qwerty123'),
                'email_verified_at' => now(),
                'role' => 'member',
                'membership_registered' => 'registered',
                'membership_status' => 'active',
                'membership_end_date' => now()->addDays(90),
                'profile_bio' => 'Anggota loyal sejak 2 tahun terakhir.',
                'profile_image' => 'user_profile\/default-user_profile.jpg',
            ]
        ];

        foreach ($users as $user) {
            User::create($user);
        }

        // Tambahan 5 member dari factory
        User::factory(5)->create([
            'role' => 'member',
            'membership_registered' => 'registered',
            'membership_status' => 'active',
        ]);
    }
}
